# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:16.16.0

pipelines:
  #  default:
  #    - step:
  #        caches:
  #          - node
  #        script: # Modify the commands below to build your repository.
  #          - npm install
  #          - npm run build
  branches:
    dev:
      - step:
          deployment: staging
          caches:
            - node
          script:
            - npm install
            - quasar build
            - pipe: atlassian/sftp-deploy:0.5.0
              variables:
                USER: $USER_STAGING
                SERVER: $SERVER_STAGING
                REMOTE_PATH: '/var/www/txto-fe'
                LOCAL_PATH: 'dist/*'
    master:
      - step:
          deployment: production
          caches:
            - node
          script:
            - npm install
            - quasar build
            - pipe: atlassian/sftp-deploy:0.5.0
              variables:
                USER: $USER_MASTER
                SERVER: $SERVER_MASTER
                REMOTE_PATH: '/var/www/txto-fe'
                LOCAL_PATH: 'dist/*'
                

